version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 32gH2dggc3d1fhg1Cbb5dbB414C
    volumes:
      - ./mysql:/var/lib/mysql
    hostname: "mysqlCon"
    ports:
      - 18409:3306

  go:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    hostname: "goCon"
    environment:
      - DATABASE_URL=root:32gH2dggc3d1fhg1Cbb5dbB414C@tcp(mysqlCon:3306)/farms?parseTime=true
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    depends_on:
      - go
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - 80:80

volumes:
  mysql:

networks:
  dbNet: {}