INSERT into Invests_In VALUES ("Danni Gerritsma", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Sanford Labone", "Lighthouse Seafood");			
INSERT into Invests_In VALUES ("Morena Pien", "Sunnybrook Stables");			
INSERT into Invests_In VALUES ("Pavel Leatherland", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Liv Burchett", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Giselle Fickling", "Autumn Ridge Farm");			
INSERT into Invests_In VALUES ("Gilli Heam", "Sunny Meadow Farm");			
INSERT into Invests_In VALUES ("Meir Cardno", "Highland Farm");			
INSERT into Invests_In VALUES ("Sophia Cockerill", "Eastwood Farms");			
INSERT into Invests_In VALUES ("Ignacius Barracks", "Crystal River Fisheries");			
INSERT into Invests_In VALUES ("Bertie Twelftree", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Sanford Labone", "Autumn Ridge Farm");			
INSERT into Invests_In VALUES ("Gilli Heam", "Whispering Pines Farmstead");			
INSERT into Invests_In VALUES ("Nikkie Windas", "Highland Farm");			
INSERT into Invests_In VALUES ("Karylin Hacquel", "Sunnybrook Stables");			
INSERT into Invests_In VALUES ("Hildagarde Bromhead", "Cedar Grove Apiary");			
INSERT into Invests_In VALUES ("Annemarie Uzzell", "Sunset Orchard");			
INSERT into Invests_In VALUES ("Noelle Bidgod", "Blue Sky Orchards");			
INSERT into Invests_In VALUES ("Liv Burchett", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Anna-diane Schukraft", "Oasis Fruit Gardens");			
INSERT into Invests_In VALUES ("Sybyl Lackeye", "Northern Light Farm");			
INSERT into Invests_In VALUES ("Catharine Placstone", "Sunny Meadow Farm");			
INSERT into Invests_In VALUES ("Zonda Janoch", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Rhoda Curlis", "Highland Farm");			
INSERT into Invests_In VALUES ("Ricca Eagle", "Autumn Ridge Farm");			
INSERT into Invests_In VALUES ("Allie Shippard", "Sunrise Farm");			
INSERT into Invests_In VALUES ("Julian Tyres", "Lighthouse Seafood");			
INSERT into Invests_In VALUES ("Ignacius Barracks", "Riverbend Cattle Co.");			
INSERT into Invests_In VALUES ("Sybyl Lackeye", "Rolling Hills Vineyard");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Pavel Leatherland", "Whispering Pines Farmstead");			
INSERT into Invests_In VALUES ("Fan Dwelley", "Northern Light Farm");			
INSERT into Invests_In VALUES ("Duffie Di Iorio", "Blossom Hill Nurseries");			
INSERT into Invests_In VALUES ("Edyth Roeby", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Gilli Heam", "Blue Sky Orchards");			
INSERT into Invests_In VALUES ("Noelle Bidgod", "Whispering Pines Farmstead");			
INSERT into Invests_In VALUES ("Lyndell Hurtic", "Cedar Grove Apiary");			
INSERT into Invests_In VALUES ("Ricca Eagle", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Sanford Labone", "Desert Bloom Farm");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Westfield Grains");			
INSERT into Invests_In VALUES ("Zonda Janoch", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Fan Dwelley", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Olivero Bedome", "Sunnybrook Stables");			
INSERT into Invests_In VALUES ("Danni Gerritsma", "Blossom Hill Nurseries");			
INSERT into Invests_In VALUES ("Ignacius Barracks", "Stone Ridge Plantation");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Island Retreat Farm");			
INSERT into Invests_In VALUES ("Gilli Heam", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Gilli Heam", "Highland Farm");			
INSERT into Invests_In VALUES ("Arty Seston", "Meadowbrook Estate");			
INSERT into Invests_In VALUES ("Olivero Bedome", "Silver Lake Dairy");			
INSERT into Invests_In VALUES ("Renaud St Ledger", "Whispering Pines Farmstead");			
INSERT into Invests_In VALUES ("Pavel Leatherland", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Lighthouse Seafood");			
INSERT into Invests_In VALUES ("Nikkie Windas", "Northern Light Farm");			
INSERT into Invests_In VALUES ("Maribel Hancke", "Silver Lake Dairy");			
INSERT into Invests_In VALUES ("Julian Tyres", "Highland Farm");			
INSERT into Invests_In VALUES ("Arty Seston", "Northern Light Farm");			
INSERT into Invests_In VALUES ("Anna-diane Schukraft", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Arty Seston", "Highland Farm");			
INSERT into Invests_In VALUES ("Olivero Bedome", "Riverbend Cattle Co.");			
INSERT into Invests_In VALUES ("Nikkie Windas", "Oasis Fruit Gardens");			
INSERT into Invests_In VALUES ("Pavel Leatherland", "Silver Lake Dairy");			
INSERT into Invests_In VALUES ("Meir Cardno", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Suzanna Fazzioli", "Silver Lake Dairy");			
INSERT into Invests_In VALUES ("Noelle Bidgod", "Rolling Hills Vineyard");			
INSERT into Invests_In VALUES ("Sanford Labone", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Lyndell Hurtic", "Misty Mountain Farm");			
INSERT into Invests_In VALUES ("Julian Tyres", "Meadowbrook Estate");			
INSERT into Invests_In VALUES ("Noelle Bidgod", "Eastwood Farms");			
INSERT into Invests_In VALUES ("Sybyl Lackeye", "Sunny Meadow Farm");			
INSERT into Invests_In VALUES ("Suzanna Fazzioli", "Desert Bloom Farm");			
INSERT into Invests_In VALUES ("Annemarie Uzzell", "Meadowbrook Estate");			
INSERT into Invests_In VALUES ("Sybyl Lackeye", "Lighthouse Seafood");			
INSERT into Invests_In VALUES ("Suzanna Fazzioli", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Hildagarde Bromhead", "Oasis Fruit Gardens");			
INSERT into Invests_In VALUES ("Noelle Bidgod", "Northern Light Farm");			
INSERT into Invests_In VALUES ("Pavel Leatherland", "Riverbend Cattle Co.");			
INSERT into Invests_In VALUES ("Giselle Fickling", "Eastwood Farms");			
INSERT into Invests_In VALUES ("Ricca Eagle", "Misty Mountain Farm");			
INSERT into Invests_In VALUES ("Noelle Bidgod", "Highland Farm");			
INSERT into Invests_In VALUES ("Arty Seston", "Sunset Orchard");			
INSERT into Invests_In VALUES ("Julian Tyres", "Crystal River Fisheries");			
INSERT into Invests_In VALUES ("Meir Cardno", "Highland Farm");			
INSERT into Invests_In VALUES ("Annemarie Uzzell", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Winslow Thowes", "Highland Farm");			
INSERT into Invests_In VALUES ("Rhoda Curlis", "Cedar Grove Apiary");			
INSERT into Invests_In VALUES ("Arty Seston", "Lighthouse Seafood");			
INSERT into Invests_In VALUES ("Morena Pien", "Autumn Ridge Farm");			
INSERT into Invests_In VALUES ("Hildagarde Bromhead", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Meir Cardno", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Rhoda Curlis", "Island Retreat Farm");			
INSERT into Invests_In VALUES ("Noelle Bidgod", "Eastwood Farms");			
INSERT into Invests_In VALUES ("Cameron Menloe", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Gilli Heam", "Winterfell Ranch");			
INSERT into Invests_In VALUES ("Bobbie Darrow", "Desert Bloom Farm");			
INSERT into Invests_In VALUES ("Anna-diane Schukraft", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Bobbie Darrow", "Meadowbrook Estate");			
INSERT into Invests_In VALUES ("Pavel Leatherland", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Giselle Fickling", "Cedar Grove Apiary");			
INSERT into Invests_In VALUES ("Edyth Roeby", "Blue Sky Orchards");			
INSERT into Invests_In VALUES ("Duffie Di Iorio", "Rolling Hills Vineyard");			
INSERT into Invests_In VALUES ("Liv Burchett", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Sophia Cockerill", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Cleavland Flory", "Sunrise Farm");			
INSERT into Invests_In VALUES ("Asia Bainbridge", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Sybyl Lackeye", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Zonda Janoch", "Highland Farm");			
INSERT into Invests_In VALUES ("Renaud St Ledger", "Westfield Grains");			
INSERT into Invests_In VALUES ("Rhoda Curlis", "Misty Mountain Farm");			
INSERT into Invests_In VALUES ("Catharine Placstone", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Asia Bainbridge", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Catharine Placstone", "Riverbend Cattle Co.");			
INSERT into Invests_In VALUES ("Allie Shippard", "Highland Farm");			
INSERT into Invests_In VALUES ("Catharine Placstone", "Autumn Ridge Farm");			
INSERT into Invests_In VALUES ("Suzanna Fazzioli", "Lighthouse Seafood");			
INSERT into Invests_In VALUES ("Annemarie Uzzell", "Island Retreat Farm");			
INSERT into Invests_In VALUES ("Noelle Bidgod", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Blossom Hill Nurseries");			
INSERT into Invests_In VALUES ("Catharine Placstone", "Northern Light Farm");			
INSERT into Invests_In VALUES ("Sanford Labone", "Sunnybrook Stables");			
INSERT into Invests_In VALUES ("Arty Seston", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Ricca Eagle", "Lighthouse Seafood");			
INSERT into Invests_In VALUES ("Fan Dwelley", "Highland Farm");			
INSERT into Invests_In VALUES ("Liv Burchett", "Northern Light Farm");			
INSERT into Invests_In VALUES ("Anna-diane Schukraft", "Autumn Ridge Farm");			
INSERT into Invests_In VALUES ("Rhoda Curlis", "Oasis Fruit Gardens");			
INSERT into Invests_In VALUES ("Ignacius Barracks", "Highland Farm");			
INSERT into Invests_In VALUES ("Anna-diane Schukraft", "Stone Ridge Plantation");			
INSERT into Invests_In VALUES ("Zonda Janoch", "Eastwood Farms");			
INSERT into Invests_In VALUES ("Abbey Szymaniak", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Pavel Leatherland", "Meadowbrook Estate");			
INSERT into Invests_In VALUES ("Lyndell Hurtic", "Autumn Ridge Farm");			
INSERT into Invests_In VALUES ("Gilli Heam", "Riverbend Cattle Co.");			
INSERT into Invests_In VALUES ("Liv Burchett", "Blossom Hill Nurseries");			
INSERT into Invests_In VALUES ("Nikkie Windas", "Sunset Orchard");			
INSERT into Invests_In VALUES ("Suzanna Fazzioli", "Autumn Ridge Farm");			
INSERT into Invests_In VALUES ("Ignacius Barracks", "Desert Bloom Farm");			
INSERT into Invests_In VALUES ("Bobbie Darrow", "Sunset Orchard");			
INSERT into Invests_In VALUES ("Asia Bainbridge", "Sunset Orchard");			
INSERT into Invests_In VALUES ("Sanford Labone", "Crystal River Fisheries");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Duffie Di Iorio", "Whispering Pines Farmstead");			
INSERT into Invests_In VALUES ("Abbey Szymaniak", "Oasis Fruit Gardens");			
INSERT into Invests_In VALUES ("Edyth Roeby", "Blossom Hill Nurseries");			
INSERT into Invests_In VALUES ("Giselle Fickling", "Crystal River Fisheries");			
INSERT into Invests_In VALUES ("Annemarie Uzzell", "Lighthouse Seafood");			
INSERT into Invests_In VALUES ("Zonda Janoch", "Eastwood Farms");			
INSERT into Invests_In VALUES ("Arty Seston", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Julian Tyres", "Riverbend Cattle Co.");			
INSERT into Invests_In VALUES ("Sophia Cockerill", "Eastwood Farms");			
INSERT into Invests_In VALUES ("Sanford Labone", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Duffie Di Iorio", "Eastwood Farms");			
INSERT into Invests_In VALUES ("Julian Tyres", "Silver Lake Dairy");			
INSERT into Invests_In VALUES ("Pavel Leatherland", "Sunnybrook Stables");			
INSERT into Invests_In VALUES ("Arty Seston", "Silver Lake Dairy");			
INSERT into Invests_In VALUES ("Nikkie Windas", "Willow Creek Homestead");			
INSERT into Invests_In VALUES ("Asia Bainbridge", "Autumn Ridge Farm");			
INSERT into Invests_In VALUES ("Annemarie Uzzell", "Blue Sky Orchards");			
INSERT into Invests_In VALUES ("Meir Cardno", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Nikkie Windas", "Riverbend Cattle Co.");			
INSERT into Invests_In VALUES ("Anna-diane Schukraft", "Island Retreat Farm");			
INSERT into Invests_In VALUES ("Karylin Hacquel", "Island Retreat Farm");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Sunset Orchard");			
INSERT into Invests_In VALUES ("Giselle Fickling", "Whispering Pines Farmstead");			
INSERT into Invests_In VALUES ("Sanford Labone", "Riverbend Cattle Co.");			
INSERT into Invests_In VALUES ("Rhoda Curlis", "Highland Farm");			
INSERT into Invests_In VALUES ("Morena Pien", "Autumn Ridge Farm");			
INSERT into Invests_In VALUES ("Ignacius Barracks", "Silver Lake Dairy");			
INSERT into Invests_In VALUES ("Annemarie Uzzell", "Northern Light Farm");			
INSERT into Invests_In VALUES ("Meir Cardno", "Riverbend Cattle Co.");			
INSERT into Invests_In VALUES ("Bertie Twelftree", "Island Retreat Farm");			
INSERT into Invests_In VALUES ("Giselle Fickling", "Winterfell Ranch");			
INSERT into Invests_In VALUES ("Suzanna Fazzioli", "Eastwood Farms");			
INSERT into Invests_In VALUES ("Meir Cardno", "Silver Lake Dairy");			
INSERT into Invests_In VALUES ("Gilli Heam", "Silver Lake Dairy");			
INSERT into Invests_In VALUES ("Olivero Bedome", "Meadowbrook Estate");			
INSERT into Invests_In VALUES ("Olivero Bedome", "Sunnybrook Stables");			
INSERT into Invests_In VALUES ("Bertie Twelftree", "Emerald Field Organics");			
INSERT into Invests_In VALUES ("Renaud St Ledger", "Lighthouse Seafood");			
INSERT into Invests_In VALUES ("Asia Bainbridge", "Rolling Hills Vineyard");			
INSERT into Invests_In VALUES ("Anna-diane Schukraft", "Highland Farm");			
INSERT into Invests_In VALUES ("Sophia Cockerill", "Sunny Meadow Farm");			
INSERT into Invests_In VALUES ("Anna-diane Schukraft", "Westfield Grains");			
INSERT into Invests_In VALUES ("Anna-diane Schukraft", "Sunset Orchard");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Blue Sky Orchards");			
INSERT into Invests_In VALUES ("Liv Burchett", "Stone Ridge Plantation");			
INSERT into Invests_In VALUES ("Danni Gerritsma", "Misty Mountain Farm");			
INSERT into Invests_In VALUES ("Annemarie Uzzell", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Liv Burchett", "Island Retreat Farm");			
INSERT into Invests_In VALUES ("Suzanna Fazzioli", "Lighthouse Seafood");			
INSERT into Invests_In VALUES ("Catharine Placstone", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Sybyl Lackeye", "Polar Ridge Farm");			
INSERT into Invests_In VALUES ("Pavel Leatherland", "Sunset Orchard");			
INSERT into Invests_In VALUES ("Fan Dwelley", "Blue Sky Orchards");			
INSERT into Invests_In VALUES ("Gilli Heam", "Blue Sky Orchards");			
INSERT into Invests_In VALUES ("Hildagarde Bromhead", "Northern Light Farm");			
INSERT into Invests_In VALUES ("Karleen Mahaddy", "Silver Lake Dairy");			
INSERT into Invests_In VALUES ("Ricca Eagle", "Westfield Grains");			
